# systemProp.http.proxyHost=127.0.0.1
# systemProp.http.proxyPort=8118

# https://developer.android.com/build/releases/gradle-plugin#default-changes

# @BindView requires a constant resource ID
android.nonFinalResIds=false

# systemProp.http.proxyHost=127.0.0.1
# systemProp.http.proxyPort=8118
# systemProp.https.proxyHost=127.0.0.1
# systemProp.https.proxyPort=8118

android.useAndroidX=true

org.gradle.jvmargs=-Xmx4g

Dhttps.protocols=TLSv1,TLSv1.1,TLSv1.2

org.gradle.jvmargs=-Dhttps.protocols=TLSv1.2,TLSv1.3

systemProp.https.protocols=TLSv1.1,TLSv1.2,TLSv1.3

# 减少编译日志输出
org.gradle.logging.level=lifecycle
org.gradle.configureondemand=true
org.gradle.parallel=true

# #4800 抑制 R8 警告
android.enableR8.fullMode=false
